[project]
name = "compendiumscribe"
version = "0.1.0"
description = "A package for creating, analyzing, and retrieving hierarchical, segmented, and keyword-tagged collections of information to augment in-context learning for AI applications."
authors = [
    {name = "B.T. Franklin", email = "brandon.franklin@gmail.com"},
]
dependencies = [
    "promptdown>=0.7.5",
    "openai>=1.40.1",
    "python-dotenv>=1.0.1",
    "click>=8.1.7",
    "colorama>=0.4.6",
    "pickled-pipeline>=0.2.0",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Code Generators",
    "Topic :: Utilities",
    "Environment :: Console",
]

[project.urls]
Homepage = "https://github.com/btfranklin/compendiumscribe"
Issues = "https://github.com/btfranklin/compendiumscribe/issues"
Changelog = "https://github.com/btfranklin/compendiumscribe/releases"
Repository = "https://github.com/btfranklin/compendiumscribe.git"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.build]
excludes = ["tests/**"]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=8.3.2",
    "flake8>=7.1.0",
]

[project.scripts]
create-compendium = "compendiumscribe.cli:main"
