from __future__ import annotations

from .research import (
    ACTION_SUMMARY_KEYS,
    DeepResearchError,
    ProgressPhase,
    ProgressStatus,
    ResearchConfig,
    ResearchProgress,
    accumulate_stream_tool_event,
    await_completion,
    build_compendium,
    coerce_optional_string,
    collect_response_text,
    collect_stream_fragments,
    compose_deep_research_prompt,
    decode_json_payload,
    default_research_plan,
    emit_progress,
    emit_trace_updates_from_item,
    execute_deep_research,
    execute_deep_research_streaming,
    extract_stream_error_message,
    extract_stream_tool_fragment,
    extract_trace_events,
    first_non_empty,
    format_query_list,
    generate_research_plan,
    get_field,
    handle_stream_event,
    iter_trace_progress_events,
    load_prompt_template,
    merge_action_payload,
    merge_response_payload,
    merge_tool_fragment,
    normalize_response_snapshot,
    parse_deep_research_response,
    simplify_action_snapshot,
    stringify_metadata_value,
    summaries_from_trace_events,
    summarize_trace_event,
    trace_event_from_item,
    trace_event_token,
    truncate_text,
    strip_leading_markdown_header,
)

# ---------------------------------------------------------------------------
# Backwards-compatible aliases (legacy private helpers)
# ---------------------------------------------------------------------------

_compose_deep_research_prompt = compose_deep_research_prompt
_decode_json_payload = decode_json_payload
_execute_deep_research = execute_deep_research
_extract_trace_events = extract_trace_events
_summaries_from_trace_events = summaries_from_trace_events
_summarize_trace_event = summarize_trace_event
_strip_leading_markdown_header = strip_leading_markdown_header

__all__ = [
    "ACTION_SUMMARY_KEYS",
    "DeepResearchError",
    "ProgressPhase",
    "ProgressStatus",
    "ResearchConfig",
    "ResearchProgress",
    "accumulate_stream_tool_event",
    "await_completion",
    "build_compendium",
    "coerce_optional_string",
    "collect_response_text",
    "collect_stream_fragments",
    "compose_deep_research_prompt",
    "decode_json_payload",
    "default_research_plan",
    "emit_progress",
    "emit_trace_updates_from_item",
    "execute_deep_research",
    "execute_deep_research_streaming",
    "extract_stream_error_message",
    "extract_stream_tool_fragment",
    "extract_trace_events",
    "first_non_empty",
    "format_query_list",
    "generate_research_plan",
    "get_field",
    "handle_stream_event",
    "iter_trace_progress_events",
    "load_prompt_template",
    "merge_action_payload",
    "merge_response_payload",
    "merge_tool_fragment",
    "normalize_response_snapshot",
    "parse_deep_research_response",
    "simplify_action_snapshot",
    "stringify_metadata_value",
    "summaries_from_trace_events",
    "summarize_trace_event",
    "trace_event_from_item",
    "trace_event_token",
    "truncate_text",
    # Legacy private aliases
    "_compose_deep_research_prompt",
    "_decode_json_payload",
    "_execute_deep_research",
    "_extract_trace_events",
    "_summaries_from_trace_events",
    "_summarize_trace_event",
    "_strip_leading_markdown_header",
]
