# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install PDM
      run: |
        python -m pip install --upgrade pip
        python -m pip install pdm
    - name: Install project
      run: pdm install --dev
    - name: Run tests
      run: pdm run pytest
    - name: Build package
      run: pdm build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.8.14
